version: '3'
services:
  loco_agent:
    image: soccer_agent_random
    hostname: agent
    env_file:
      - docker/agent/docker.env
    build:
      context: ./
      dockerfile: docker/agent/Dockerfile_AgentSoccer_random
